import { Project } from './Project';

export const MOCK_PROJECTS = [
  new Project({
    id: 1,
    name: 'Cleanliness Campaign',
    description: 'Organize a community cleanliness campaign to keep our city clean and green.',
    contractTypeId: 3,
    contractSignedOn: '2023-01-15T09:00:00.000Z',
    isActive: false,
  }),
  new Project({
    id: 2,
    name: 'Youth Sports Program',
    description: 'Promote sports among youth by organizing sports events and training programs.',
    contractTypeId: 4,
    contractSignedOn: '2023-02-20T14:30:00.000Z',
    isActive: true,
  }),
  new Project({
    id: 3,
    name: 'Tree Planting Initiative',
    description: 'Plant trees in public areas to improve air quality and beautify the city.',
    contractTypeId: 2,
    contractSignedOn: '2023-03-10T11:45:00.000Z',
    isActive: true,
  }),
  new Project({
    id: 4,
    name: 'Community Health Fair',
    description: 'Organize a health fair to provide free medical checkups and information to residents.',
    contractTypeId: 1,
    contractSignedOn: '2023-04-18T13:15:00.000Z',
    isActive: true,
  }),
  new Project({
    id: 5,
    name: 'Cultural Festival',
    description: 'Celebrate the diversity of our community with a cultural festival showcasing food, music, and art.',
    contractTypeId: 2,
    contractSignedOn: '2023-05-25T17:30:00.000Z',
    isActive: true,
  }),
  new Project({
    id: 6,
    name: 'Elderly Care Program',
    description: 'Provide support and companionship to elderly residents in our community.',
    contractTypeId: 3,
    contractSignedOn: '2023-06-10T10:00:00.000Z',
    isActive: true,
  }),
  new Project({
    id: 7,
    name: 'Community Garden Project',
    description: 'Create a community garden for residents to grow their own produce.',
    contractTypeId: 4,
    contractSignedOn: '2023-07-05T09:30:00.000Z',
    isActive: true,
  }),
  new Project({
    id: 8,
    name: 'Youth Education Program',
    description: 'Offer educational workshops and tutoring for children and teenagers in our community.',
    contractTypeId: 3,
    contractSignedOn: '2023-08-12T14:00:00.000Z',
    isActive: true,
  }),
  new Project({
    id: 9,
    name: 'Community Cleanup Day',
    description: 'Engage residents in a day of cleaning and beautifying our neighborhood.',
    contractTypeId: 1,
    contractSignedOn: '2023-09-20T08:45:00.000Z',
    isActive: false,
  }),
  new Project({
    id: 10,
    name: 'Tree Planting Initiative',
    description: 'Plant trees in public areas to improve air quality and beautify the city.',
    contractTypeId: 2,
    contractSignedOn: '2023-03-10T11:45:00.000Z',
    isActive: true,
  }),
  new Project({
    id: 11,
    name: 'Community Health Fair',
    description: 'Organize a health fair to provide free medical checkups and information to residents.',
    contractTypeId: 1,
    contractSignedOn: '2023-04-18T13:15:00.000Z',
    isActive: true,
  }),
  new Project({
    id: 12,
    name: 'Cultural Festival',
    description: 'Celebrate the diversity of our community with a cultural festival showcasing food, music, and art.',
    contractTypeId: 2,
    contractSignedOn: '2023-05-25T17:30:00.000Z',
    isActive: true,
  }),
];